# Custom configuration for analyzing CodeSight's source code
include_extensions = [".py", ".md", ".rst", ".toml", ".yaml"]  # Include all Python files
truncate_py_literals = 10  # Show more elements in literals for better readability
include_files = [".flake8"]  # Include flake8 configuration
