[tool.poetry]
name = "codesight"
version = "0.1.0"
description = "Apple-simple code collation tool for LLM context generation"
authors = ["Matt Silverman"]
license = "MIT"
readme = "README.md"
packages = [{include = "codesight", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
click = ">=8.1.3,<8.2.0"
pyperclip = ">=1.8.2,<1.9.0"
tiktoken = ">=0.8.0,<0.9.0"
toml = ">=0.10.2"
rich = ">=13.0.0"
chardet = ">=5.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
mypy = "^1.9.0"
black = "^24.3.0"
flake8 = "^7.0.0"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
codesight = "codesight.cli:main"

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
