name: CI

on:
  # Run on PRs to main
  pull_request:
    branches: [main]
  # Run on pushes to main, but not when it's just a tag
  push:
    branches: [main]
    tags-ignore: ["*"] # Ignore all tags

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1

      - name: Install dependencies
        run: poetry install

      - name: Run formatting check
        run: |
          poetry run ruff format --check .
          poetry run isort --check-only --profile black .

      - name: Run tests
        run: poetry run pytest tests/

      - name: Run linting
        run: |
          poetry run ruff check .
          poetry run black --check .
          poetry run mypy src tests

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=src/codesight --cov-branch --cov-report=xml --cov-report=term-missing --cov-fail-under=80 tests/

      - name: Verify coverage file
        run: |
          ls -la coverage.xml
          echo "Coverage file exists and has size: $(stat -f%z coverage.xml) bytes"

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true
          working-directory: .

      - name: Build package
        run: poetry build
