name: CI

on:
  # Run on PRs to main
  pull_request:
    branches: [main]
  # Run on pushes to main, but not when it's just a tag
  push:
    branches: [main]
    tags-ignore: ["*"] # Ignore all tags

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1

      - name: Install dependencies
        run: poetry install

      # Single formatting check step
      - name: Check code style
        run: |
          poetry run ruff format --check .
          poetry run isort --check-only --profile black .

      # Single type checking step
      - name: Check types
        run: poetry run mypy src tests

      # Single test step with coverage
      - name: Run tests with coverage
        run: |
          poetry run pytest tests/ --cov=src/codesight --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage.xml
          fail_ci_if_error: true

      - name: Build package
        run: poetry build
