name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Make scripts executable
      run: |
        chmod +x ./codesight.sh
        chmod +x ./install.sh
        find ./commands -name "*.sh" -exec chmod +x {} \;
        find ./utils -name "*.sh" -exec chmod +x {} \;
    - name: Run help command
      run: |
        ./codesight.sh help
    - name: Test initialization
      run: |
        ./codesight.sh init
        test -d ./.codesight || exit 1
    - name: Check version
      run: |
        ./codesight.sh | grep -q "CodeSight version" || exit 1